pipeline {
    agent any

    tools {
        python 'Python3'
    }

    environment {
        GITHUB_CREDENTIALS = credentials('github-token') // Use your actual ID
    }

    stages {
        stage('Clone repository') {
            steps {
                git credentialsId: "${GITHUB_CREDENTIALS}", url: 'https://github.com/ashenafi-16/alx-backend-python'
            }
        }

        stage('Setup Python Environment') {
            steps {
                withPythonEnv('Python3') {
                    sh 'pip install -r messaging_app/requirements.txt'
                }
            }
        }

        stage('Run Tests') {
            steps {
                withPythonEnv('Python3') {
                    sh 'pytest messaging_app/tests/ --junitxml=report.xml'
                }
            }
        }

        stage('Publish Report') {
            steps {
                junit 'report.xml'
            }
        }
    }
}
