apiVersion: v1
kind: Service
metadata:
  name: messaging-app-service
  labels:
    app: messaging-app
spec:
  type: ClusterIP
  selector:
    app: messaging-app
    version: blue  # Start with blue deployment (current version)
  ports:
    - name: http
      port: 8000
      targetPort: 8000
---
# Service for blue deployment (for direct access during testing)
apiVersion: v1
kind: Service
metadata:
  name: messaging-app-blue
  labels:
    app: messaging-app
    version: blue
spec:
  type: ClusterIP
  selector:
    app: messaging-app
    version: blue
  ports:
    - name: http
      port: 8000
      targetPort: 8000
---
# Service for green deployment (for direct access during testing)
apiVersion: v1
kind: Service
metadata:
  name: messaging-app-green
  labels:
    app: messaging-app
    version: green
spec:
  type: ClusterIP
  selector:
    app: messaging-app
    version: green
  ports:
    - name: http
      port: 8000
      targetPort: 8000
