apiVersion: apps/v1
kind: Deployment
metadata:
  name: messaging-app-blue
  labels:
    app: messaging-app
    version: blue
spec:
  replicas: 3
  selector:
    matchLabels:
      app: messaging-app
      version: blue
  template:
    metadata:
      labels:
        app: messaging-app
        version: blue
    spec:
      containers:
        - name: web
          image: messaging-app:2.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: DJANGO_ALLOWED_HOSTS
              value: "*"
            - name: MYSQL_DATABASE
              value: "messaging_db"
            - name: MYSQL_USER
              value: "messaging_user"
            - name: MYSQL_PASSWORD
              value: "messaging_password123"
            - name: MYSQL_HOST
              value: "db"
            - name: MYSQL_PORT
              value: "3306"
          readinessProbe:
            tcpSocket:
              port: 8000
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 20
